import type { ComponentType, SVGProps } from 'react';
import {
  ArchiveBoxIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowTopRightOnSquareIcon,
  BanknotesIcon,
  BeakerIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  FaceSmileIcon,
  HeartIcon,
  HomeIcon,
  InformationCircleIcon,
  LinkIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  PaperClipIcon,
  PauseCircleIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlusCircleIcon,
  PlusIcon,
  StopCircleIcon,
  TrashIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';

export type AppIcon = ComponentType<SVGProps<SVGSVGElement>>;

export const eventTypeIcons: Record<string, AppIcon> = {
  'Consulta Médica': HeartIcon,
  'Consulta Dental': FaceSmileIcon,
  Urgencia: ExclamationTriangleIcon,
  Cirugía: BuildingOffice2Icon,
  Examen: BeakerIcon,
  Receta: DocumentTextIcon,
  Otro: ClipboardDocumentListIcon,
};

export const commonIcons = {
  archive: ArchiveBoxIcon,
  back: ArrowLeftIcon,
  calendar: CalendarDaysIcon,
  check: CheckCircleIcon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  clipboard: ClipboardDocumentListIcon,
  copy: DocumentDuplicateIcon,
  clock: ClockIcon,
  close: XMarkIcon,
  danger: XCircleIcon,
  document: DocumentIcon,
  edit: PencilSquareIcon,
  home: HomeIcon,
  info: InformationCircleIcon,
  link: LinkIcon,
  lock: LockClosedIcon,
  money: BanknotesIcon,
  photo: PhotoIcon,
  pickup: CalendarDaysIcon,
  plus: PlusIcon,
  plusCircle: PlusCircleIcon,
  record: MicrophoneIcon,
  retry: ArrowPathIcon,
  search: MagnifyingGlassIcon,
  stop: StopCircleIcon,
  stopAction: PauseCircleIcon,
  treatments: BeakerIcon,
  trash: TrashIcon,
  upload: PaperClipIcon,
  externalLink: ArrowTopRightOnSquareIcon,
};
